- name: Facts
  block:
    - name: Get instances facts
      ec2_instance_facts:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: "{{ region }}"
      register: result

#    - name: Instances ID
#      debug:
#        msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
#      loop: "{{ result.instances }}"

    - name: De-provision instance(s)
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
#        key_name: "{{ key_name }}"
        instance_tags:
          tag_id: "{{ id }}"
#       group_id: "{{ result_sec_group.group_id }}"
#        image: "{{ image }}"
#        instance_type: t2.large
        region: "{{ region }}"
        state: absent
        instance_id: "{{ item.instance_id }}"
        wait: true
        count: 1
      loop: "{{ result.instances }}"
